site_name: Recipe Collection
site_url: https://carolekoziol.github.io/recipes
site_description: Recipe Collection

pages:
- Home: 'index.md'
- Main Dishes:
    - 'Omni':
        - 'Italian':
            - 'Tomato-Based Pasta Sauce': 'mains/standard_tomato_based_pasta_sauce.md'
    - 'Vegetarian':
        - 'Chinese':
            - "General Tao Noodle Bowl": 'mains/general_tao_noodle_bowl.md'
