site_name: The Koziol Recipe Collection
site_url: https://carolekoziol.github.io/recipes
site_description: Recipe Collection
theme: mkdocs

nav:
- Recipe Index:
    - Appetizers & Snacks:
        - Placeholder:
            - Food: ''
    - Beverages:
        - Placeholder:
            - Food: ''
    - Breads:
        - Placeholder:
            - Food: ''
    - Breakfasts & Brunchs:
        - Roasted Brussel Sprouts & Bacon (P, DF, GF) : 'sides/roasted_brussel_sprouts_bacon_apples.md'
        - Shakshuka (P, DF, GF): 'breakfast/shakshuka.md'
        - Oatmeal (DF, GF, Ve, V): 'breakfast/oatmeal.md'
    - Cheeses:
        - Placeholder:
            - Food: ''
    - Dehydrator:
        - Placeholder:
            - Food: ''
    - Desserts:
        - Placeholder:
            - Food: ''
    - Main Courses:
        - North American: 
            - Big Bhaji Burger (Ve, GF): 'main_course/big_bhaji_burger.md'
            - Tofu Quiche (Ve, GF) : 'main_course/tofu_quiche.md'
            - Roasted Cauliflower Steaks (Ve, P, GF): 'main_course/roasted_cauliflower_steaks.md'
        - Bowls:
            - General Tao Noodle Bowl (Ve, GF): 'main_course/general_tao_noodle_bowl.md'
            - Bibimbap: 'main_course/bibimbap.md'
            - Loco Moco: 'main_course/loco_moco.md'
        - Casseroles:
            - Jambalaya (P, DF, GF): 'main_course/jambalaya.md'
        - Curry & Pad Thai: 
            - Coconut Chickpea Curry: 'main_course/coconut_chickpea_curry.md'
            - Robyn Thai Red Curry Chicken: 'main_course/robyn_thai_red_curry_chicken.md'
            - Noodle-Free Pad Thai: 'main_course/noodle_free_pad_thai.md'
        - Mediterranean: 
            - Donair: 'main_course/donair.md'
            - Falafel: 'main_course/falafel.md'
        - Stir-Fry: 
            - General Tao Chicken: 'main_course/general_tao_chicken.md'
        - Indian:
            - Aloo Mushroom Masala: 'main_course/mushroom_masala.md'
            - Baingan Bharta: 'main_course/baingan_bharta.md'
            - Dairy-Free Butter Chicken: 'main_course/dairy_free_butter_chicken.md'
        - Pasta:
            - Cabbage Stroganoff: 'main_course/cabbage_stroganoff.md'
    - Salads:
        - Placeholder:
            - Food: ''
    - Sides:
        - Vegetable:
            - Aloo Palak: 'sides/aloo_palak.md'
            - Grilled Onions: 'sides/grilled_onions.md'
            - Mushroom spinach potstickers: 'sides/mushroom_spinach_potstickers.md'
            - Roasted Brussel Sprouts with Bacon and Apples: 'sides/roasted_brussel_sprouts_bacon_apples.md'
            - Roasted Butternut Squash: 'sides/roasted_butternut_squash.md'
            - Roasted Maple Squash: 'sides/roasted_maple_squash.md'
            - Roasted Radishes: 'sides/roasted_radishes.md'
            - Squished Baby Potatoes: 'sides/squished_baby_potatoes.md'
            - Stir Fry Bean Sprouts with Fried Garlic: 'sides/stir_fry_bean_sprouts.md'
            - Succotash: 'sides/succotash.md'
            - Zucchini Fritters: 'sides/zucchini_fritters.md'
        - Legumes:
            - Baked Beans: 'sides/baked_beans_instant_pot.md'
        - Rice:
            -  Food: ''
    - Soups & Stews:
        - Soups:
            - Avgolemono Chicken Soup: 'soups_stews/avgolemono_chicken_soup.md'            
            - French Canadian Pea Soup: 'soups_stews/soupe_pois_québécoise_french_canadian_pea_soup.md'
            - Lentil Soup: 'soups_stews/lentil_soup.md'
        - Stews:
            - Curried Bean and Brussels Stew with Roasted Squash: 'soups_stews/curried_bean_brussels_stew_squash.md'           
    - Sauces/Dips/Condiments:
        - Sauce:
            - Tomato-Based Pasta Sauce: 'sauces/standard_tomato_based_pasta_sauce.md'
- Basics:
    - Broth:
        - Bone Broth: ''
        - Vegetable Broth: ''
    - Fermentation:
        - Kimchi: ''
        - Sourkraut: ''    
    - Sausage: ''
    - Sourdough Starter: ''  
    - Tofu:
        - Soy tofu: ''
        - Chickpea tofu: ''
    - Tempeh: '' 
- About:
    - 'Placeholder'
