site_name: The Koziol Recipe Collection
site_url: https://carolekoziol.github.io/recipes
site_description: Recipe Collection
theme: mkdocs

nav:
- Recipe Index:
    - Appetizers & Snacks:
        - Snacks:
            - Fruity Coconut Popsicles (P, Ve, GF): 'appetizers_snacks/fruity_coconut_popsicles.md'
            - Chocolate Nut Butter Banana Popsicles(P, Ve, GF): 'appetizers_snacks/chocolate_nut_butter_popsicles.md'
    - Beverages:
        - Placeholder:
            - Food: ''
    - Breads:
        - Pizza Crusts (Ve, P, GF, DF): 'breads/pizza_crusts.md'
    - Breakfasts & Brunchs:
        - French Crepe With filling (V, DF): 'breakfast/french_crepe_filling.md'
        - Roasted Brussel Sprouts & Bacon (P, DF, GF) : 'sides/roasted_brussel_sprouts_bacon_apples.md'
        - Shakshuka (P, DF, GF): 'breakfast/shakshuka.md'
        - Oatmeal (Ve, V, DF, GF): 'breakfast/oatmeal.md' 
    - Dehydrator:
        - Placeholder:
            - Food: ''
    - Desserts:
        - Placeholder:
            - Food: ''
    - Main Courses:
        - North American: 
            - Big Bhaji Burger (Ve, GF): 'main_course/big_bhaji_burger.md'
            - Buffalo Cauliflower Burger (Ve, GF): 'main_course/buffalo_cauliflower_burger.md'
            - Paleo Chicken Nuggets (P, GF, DF): 'main_course/chicken_nuggets.md'
            - Pizza (Ve, P, GF, DF): ''
            - Tofu Quiche (Ve, GF) : 'main_course/tofu_quiche.md'
            - Roasted Cauliflower Steaks (Ve, P, GF): 'main_course/roasted_cauliflower_steaks.md'
        - Bowls:
            - General Tao Noodle Bowl (Ve, GF): 'main_course/general_tao_noodle_bowl.md'
            - Bibimbap: 'main_course/bibimbap.md'
            - Loco Moco: 'main_course/loco_moco.md'
        - Casseroles:
            - Jambalaya (P, DF, GF): 'main_course/jambalaya.md'
            - Sausage and Slaw Skillet (P, GF): 'main_course/sausage_slaw_skillet.md'
            - Spanish Paella (Ve, GF): 'main_course/paella.md'
        - Curry & Pad Thai: 
            - Coconut Chickpea Curry (Ve, GF): 'main_course/coconut_chickpea_curry.md'
            - Robyn's Chicken Red Thai Curry (P, DF, GF): 'main_course/robyn_red_thai_curry_chicken.md'
            - Noodle-Free Pad Thai (Ve, P, GF): 'main_course/noodle_free_pad_thai.md'
        - Mediterranean: 
            - Donair: 'main_course/donair.md'
            - Falafel (Ve, GF): 'main_course/falafel.md'
        - Mexican: 
            - Flautas (VE, DF): 'main_course/flautas.md'            
        - Stir-Fry: 
            - General Tao Chicken: 'main_course/general_tao_chicken.md'
        - Indian:
            - Aloo Mushroom Masala (Ve, GF): 'main_course/mushroom_masala.md'
            - Baingan Bharta (Ve, GF): 'main_course/baingan_bharta.md'
            - Dairy-Free Butter Chicken (P, GF, DF): 'main_course/dairy_free_butter_chicken.md'
        - Pasta:
            - Cabbage Stroganoff (P, Ve, DF, GF): 'main_course/cabbage_stroganoff.md'
            - Dan Dan Chae Noodles (Ve): 'main_course/dan_japchae_noodles.md'
    - Salads:
        - Placeholder:
            - Food: ''
    - Sides:
        - Vegetable:
            - Aloo Palak (Ve, GF): 'sides/aloo_palak.md'
            - Grilled Onions (Ve, P, GF): 'sides/grilled_onions.md'
            - Mushroom spinach potstickers (Ve, P, GF): 'sides/mushroom_spinach_potstickers.md'
            - Roasted Brussel Sprouts with Bacon and Apples (P, DF, GF): 'sides/roasted_brussel_sprouts_bacon_apples.md'
            - Roasted Butternut Squash (Ve, P, GF): 'sides/roasted_butternut_squash.md'
            - Roasted Maple Squash (Ve, P, GF): 'sides/roasted_maple_squash.md'
            - Roasted Radishes (Ve, P, GF): 'sides/roasted_radishes.md'
            - Squished Baby Potatoes (Ve, GF): 'sides/squished_baby_potatoes.md'
            - Stir Fry Bean Sprouts with Fried Garlic (Ve, P, GF): 'sides/stir_fry_bean_sprouts.md'
            - Succotash (Ve, GF): 'sides/succotash.md'
            - Zucchini Fritters (Ve, P, GF): 'sides/zucchini_fritters.md'
        - Beans:
            - Baked Beans (Ve, GF): 'sides/baked_beans_instant_pot.md'
            - BLack eyed peas Curry (Ve, GF): 'sides/black_eyed_peas_curry_instant_pot.md'
        - Rice:
            -  Food: ''
    - Soups & Stews:
        - Soups:
            - Avgolemono Chicken Soup: 'soups_stews/avgolemono_chicken_soup.md'            
            - French Canadian Pea Soup (Ve, GF): 'soups_stews/soupe_pois_québécoise_french_canadian_pea_soup.md'
            - Lentil Soup (Ve, GF): 'soups_stews/lentil_soup.md'
            - Spicy Sausage White Bean Soup (P, DF, GF): 'soups_stews/spicy_sausage_white_bean_soup.md'
        - Stews:
            - Curried Bean and Brussels Stew (Ve, P, GF): 'soups_stews/curried_bean_brussels_stew_squash.md'
        - Chowders:
            - Succotash Chowder (Ve, GF): 'soups_stews/succotash_chowder.md'                   
    - Sauces/Dips/Cheezes:
        - Cheezes:
            - Cheeze Sauce (Ve, GF): 'sauces/cheeze_sauce.md'
        - Dips:
            - Buffalo Chicken Dip (P, DF, GF): 'sauces/buffalo_chicken_dip.md'
            - Cretons (P, DF, GF): 'sauces/cretons.md'
            - Roasted Salsa (P, Ve, GF): 'sauces/roasted_salsa.md'
            - Vegan Spinach Dip (Ve, GF): 'sauces/vegan_spinach_dip.md'
        - Sauces:
            - Honey Garlic Sauce (P, Ve, GF): 'sauces/honey_garlic_sauce.md'  
            - Pizza Sauce (P, Ve, GF): 'sauces/pizza_sauce.md'
            - Spaghetti Sauce (P, GF): 'sauces/spaghetti_sauce.md'
- Basics:
    - Broth:
        - Bone Broth: ''
        - Vegetable Broth: ''
    - Fermentation:
        - Kimchi: ''
        - Sourkraut: ''
        - Jun: ''
        - Kombucha: ''        
    - Sausage: ''
    - Seitan: ''
    - Sourdough Starter: ''  
    - Tofu:
        - Soy tofu: ''
        - Chickpea tofu: ''
    - Tempeh: '' 
- About:
    - Measurements Equivalent: 'measurements/measurements_conversions.md'
