site_name: The Koziol Recipe Collection
site_url: https://carolekoziol.github.io/recipes
site_description: Recipe Collection
theme: mkdocs

nav:
- Recipe Index:
    - Appetizers & Snacks:
        - Appetizers:
            - Bruschetta (Ve, DF): 'appetizers_snacks/bruschetta.md'
            - Eggplant Caponata (Ve, P, DF, GF): 'appetizers_snacks/eggplant_caponata.md'
            - Italian Roasted Red Pepper Antipasto (Ve, DF): 'appetizers_snacks/roasted_red_pepper_antipasto.md'
        - Snacks:
            - Fruity Coconut Popsicles (P, Ve, GF): 'appetizers_snacks/fruity_coconut_popsicles.md'
            - Chocolate Nut Butter Banana Popsicles(P, Ve, GF): 'appetizers_snacks/chocolate_nut_butter_popsicles.md'
    - Beverages:
        - Dairy-Free Eggnog: 'beverages/dairy_free_eggnog.md'
    - Breads:
        - Italian Pizza Dough (Ve, P, GF, DF): 'breads/italian_pizza_dough.md'
        - North American Pizza Crusts (Ve, P, GF, DF): 'breads/pizza_crusts.md'
        - Pretzel Sourdough Discard: ''
        - Sourdough Bread: 'breads/sourdough_bread.md'
    - Breakfasts & Brunchs:
        - French Crepe With filling (V, DF): 'breakfast/french_crepe_filling.md'
        - Roasted Brussel Sprouts & Bacon (P, DF, GF) : 'sides/roasted_brussel_sprouts_bacon_apples.md'
        - Shakshuka (P, DF, GF): 'breakfast/shakshuka.md'
        - Oatmeal (Ve, V, DF, GF): 'breakfast/oatmeal.md' 
    - Dehydrator:
        - Placeholder:
            - Food: ''
    - Desserts:
        - Cake/Cookies:
            - Mug Brownies: 'desserts/mug_brownie.md'
            - Cheese cake (Ve, DF): 'desserts/vegan_cheese_cake.md'
            - Gingersnap cookies (GF, DF): 'desserts/gf_gingersnap_cookies.md'
        - Frosting:
            - For Cake and Cupcake: 'desserts/vegan_frosting.md'
        - Fudge:
            - Vegan Chocolate (Ve, DF): 'desserts/vegan_fudge.md'
        - Crust:
            - Gingersnap Pie Crust (GF, DF): 'desserts/gingersnap_pie_crust.md'
        - Pie:
            - Pumpkin Pie (Ve, DF): 'desserts/vegan_pumpkin_pie.md'
            - Lemon Meringue Pie (DF): 'desserts/lemon_meringue_pie.md'
        - Toppings:
            - Whipped Cream: 'desserts/coconut_whipped_cream.md'
    - Main Courses:
        - North American: 
            - Big Bhaji Burger (Ve, GF): 'main_course/big_bhaji_burger.md'
            - Buffalo Cauliflower Burger (Ve, GF): 'main_course/buffalo_cauliflower_burger.md'
            - Carrot Dogs (Ve, DF): 'main_course/carrot_dogs.md'
            - Chicken Nuggets (P, GF, DF): 'main_course/chicken_nuggets.md'
            - Meat pie (Tourtière): 'main_course/meat_pie.md'
            - Pizza (Ve, P, GF, DF): ''
            - Tofu Quiche (Ve, GF) : 'main_course/tofu_quiche.md'
            - Roasted Cauliflower Steaks (Ve, P, GF): 'main_course/roasted_cauliflower_steaks.md'
            - Roasted Leg of Lamb (P, GF): 'main_course/roasted_leg_lamb.md'
        - Bowls:
            - General Tao Noodle Bowl (Ve, GF): 'main_course/general_tao_noodle_bowl.md'
            - Bibimbap: 'main_course/bibimbap.md'
            - Loco Moco: 'main_course/loco_moco.md'
        - Casseroles:
            - Jambalaya (P, DF, GF): 'main_course/jambalaya.md'
            - Loaded Cauliflower Bake Casserole (P, DF, GF): 'main_course/loaded_cauliflower_bake_casserole.md'
            - Sausage and Slaw Skillet (P, GF): 'main_course/sausage_slaw_skillet.md'
            - Sausage Casserole (P, DF, GF): 'main_course/sausage_casserole.md'
            - Shepherd Pie: 'main_course/shepherd_pie.md'
            - Spanish Paella (Ve, GF): 'main_course/paella.md'
            - Taco Casserole (P, DF): 'main_course/taco_casserole.md'
        - Curry & Pad Thai: 
            - Coconut Chickpea Curry (Ve, GF): 'main_course/coconut_chickpea_curry.md'
            - Robyn's Chicken Red Thai Curry (P, DF, GF): 'main_course/robyn_red_thai_curry_chicken.md'
            - Noodle-Free Pad Thai (Ve, P, GF): 'main_course/noodle_free_pad_thai.md'
            - Vegan Pad Thai (Ve, DF): 'main_course/vegan_pad_thai.md'
        - Mediterranean: 
            - Donair: 'main_course/donair.md'
            - Falafel (Ve, GF): 'main_course/falafel.md'
            - Mujaddara (Ve, DF, GF): 'main_course/mujaddara.md'
        - Mexican: 
            - Flautas (VE, DF): 'main_course/flautas.md'
        - Pizza: 
            - North American Pizzas: 'main_course/pizza.md'
            - Rustic Italian Pizza: 'main_course/rustic_italian _pizza.md'   
        - Asian: 
            - General Tao Chicken: 'main_course/general_tao_chicken.md'
            - Peanut Noodles (Ve, DF): 'main_course/peanut_noodles.md'
        - Indian:
            - Aloo Mushroom Masala (Ve, GF): 'main_course/mushroom_masala.md'
            - Baingan Bharta (Ve, GF): 'main_course/baingan_bharta.md'
            - Dairy-Free Butter Chicken (P, GF, DF): 'main_course/dairy_free_butter_chicken.md'
        - Pasta:
            - Cabbage Stroganoff (P, Ve, DF, GF): 'main_course/cabbage_stroganoff.md'
            - Dan Dan Chae Noodles (Ve): 'main_course/dan_japchae_noodles.md'
            - Fettuccini Alfredo (Ve, DF, GF): 'main_course/vegan_alfredo.md'
            - Lasagna (Ve, DF): 'main_course/lasagna.md'
            - Pumpkin Penne (Ve, DF, GF): 'main_course/pumpkin_penne.md'
            - Noodles with Corn and Rosemary Sauce (Ve, DF, GF): 'main_course/noodles_corn_rosemary_sauce.md'
            - Noodles with Black Bean Sauce (Ve, DF, GF): 'main_course/noodle_pepper_black_bean_sauce.md'
            - Tofu Mushroom Stroganoff (Ve, DF, GF): 'main_course/tofu_mushroom_stroganoff.md'
    - Salads:
        - Placeholder:
            - Food: ''
    - Sides:
        - Vegetable:
            - Aloo Palak (Ve, GF): 'sides/aloo_palak.md'
            - Beet Glaze (V, P, DF, GF): 'sides/beet_glaze.md'
            - Carrot Glaze (V, P, DF, GF): 'sides/carrot_glaze.md'
            - Grilled Onions (Ve, P, GF): 'sides/grilled_onions.md'
            - Mushroom spinach potstickers (Ve, P, GF): 'sides/mushroom_spinach_potstickers.md'
            - Roasted Brussel Sprouts with Bacon and Apples (P, DF, GF): 'sides/roasted_brussel_sprouts_bacon_apples.md'
            - Roasted Butternut Squash (Ve, P, GF): 'sides/roasted_butternut_squash.md'
            - Roasted Maple Squash (Ve, P, GF): 'sides/roasted_maple_squash.md'
            - Roasted Radishes (Ve, P, GF): 'sides/roasted_radishes.md'
            - Squished Baby Potatoes (Ve, GF): 'sides/squished_baby_potatoes.md'
            - Stir Fry Bean Sprouts with Fried Garlic (Ve, P, GF): 'sides/stir_fry_bean_sprouts.md'
            - Succotash (Ve, GF): 'sides/succotash.md'
            - Italian Roasted Red Pepper Antipasto (Ve, DF): 'appetizers_snacks/roasted_red_pepper_antipasto.md'
            - Italian Style Zucchini and Mushroom (P, Ve, GF): 'appetizers_snacks/italian_zucchini_mushrooms.md'
            - Vegetables Fritters (Ve, P, GF): 'sides/vegetables_fritters.md'
        - Beans:
            - Baked Beans (Ve, GF): 'sides/baked_beans_instant_pot.md'
            - Black eyed peas Curry (Ve, GF): 'sides/black_eyed_peas_curry_instant_pot.md'
        - Rice:
            -  Food: ''
    - Soups & Stews:
        - Soups:
            - Avgolemono Chicken Soup: 'soups_stews/avgolemono_chicken_soup.md'            
            - French Canadian Pea Soup (Ve, GF): 'soups_stews/soupe_pois_québécoise_french_canadian_pea_soup.md'
            - Lentil Soup (Ve, GF): 'soups_stews/lentil_soup.md'
            - Spicy Sausage White Bean Soup (P, DF, GF): 'soups_stews/spicy_sausage_white_bean_soup.md'
        - Stews:
            - Curried Bean and Brussels Stew (Ve, P, GF): 'soups_stews/curried_bean_brussels_stew_squash.md'
            - Hungarian Goulash (V, DF, GF): 'soups_stews/hungarian_goulash.md'
        - Chowders:
            - Succotash Chowder (Ve, GF): 'soups_stews/succotash_chowder.md'                   
    - Sauces/Dips/Cheezes:
        - Cheezes:
            - Cheeze Sauce (Ve, GF): 'sauces/cheeze_sauce.md'
            - Vegan Heavy Cream (Ve, GF, P, GF): 'sauces/vegan_heavy_cream.md'
            - Vegan Mozzarella (Ve, GF, P, GF): 'sauces/vegan_mozzarella.md'
            - Vegan Parmesan (Ve, GF, P, GF): 'sauces/vegan_parmesan.md'
            - Vegan Ricotta (Ve, GF, P, GF): 'sauces/vegan_ricotta.md'
            - Vegan Sour Cream (Ve, GF, P, GF): 'sauces/vegan_sour_cream.md'
        - Dips:
            - Buffalo Chicken Dip (P, DF, GF): 'sauces/buffalo_chicken_dip.md'
            - Cretons (P, DF, GF): 'sauces/cretons.md'
            - Roasted Salsa (P, Ve, GF): 'sauces/roasted_salsa.md'
            - Baked Spinach Dip (Ve, GF): 'sauces/vegan_baked_spinach_dip.md'
        - Sauces:
            - Authentic Italian Tomato Sauce (P, Ve, GF): 'sauces/italian_tomato_sauce.md'  
            - Honey Garlic Sauce (P, Ve, GF): 'sauces/honey_garlic_sauce.md'  
            - Pizza Sauce (P, Ve, GF): 'sauces/pizza_sauce.md'
            - Spaghetti Sauce (P, GF): 'sauces/spaghetti_sauce.md'
- Basics:
    - Broth:
        - Bone Broth: ''
        - Vegetable Broth: ''
    - Fermentation:
        - Kimchi: ''
        - Sourkraut: ''
        - Jun: ''
        - Kombucha: ''      
    - Pasta:
        - Authentic Italian Egg Pasta: ''
        - Authentic Italian Gnocchi: ''  
    - Homemade Sausages: 'basics/sausage'
    - Sourdough Starter:  'basics/sourdough_starter.md'   
    - Tofu:
        - Tofu Marinades: 'basics/marinating_tofu.md'
        - How to Make Tofu:
            - Soy Tofu: ''
            - Chickpea Tofu: ''
    - Tempeh: '' 
- About:
    - Measurements Equivalent: 'measurements/measurements_conversions.md'
