site_name: Recipes
site_url: https://carolekoziol.github.io/recipes
site_description: Recipe Collection
theme: yeti

nav:
- Appetizers:
    - Placeholder:
        - Food: ''
- Breads:
    - Placeholder:
        - Food: ''
- Breakfast:
    - Placeholder:
        - Food: ''
- Desserts:
    - Placeholder:
        - Food: ''
- Drinks:
    - Placeholder:
        - Food: ''
- Entrees:
    - Chinese:
        - General Tao Noodle Bowl: 'entrees/general_tao_noodle_bowl.md'
    - Indian:
        - Baingan Bharta: 'entrees/baingan_bharta.md'
    - Pasta:
        - Cabbage Stroganoff: 'entrees/cabbage_stroganoff.md'
        - Tomato-Based Pasta Sauce: 'entrees/standard_tomato_based_pasta_sauce.md'
- Sauces:
    - Placeholder:
        - Food: ''
- Salads:
    - Placeholder:
        - Food: ''
- Side Dishes:
    - Placeholder:
        - Food: ''
- Snacks:
    - Placeholder:
        - Food: ''
