site_name: The Koziol Recipe Collection
site_url: https://carolekoziol.github.io/recipes
site_description: Recipe Collection
theme: mkdocs

nav:
- Recipe Index:
    - Appetizers:
        - Balsamic Tomato Slices (Ve, P, DF, GF): 'appetizers/balsamic_tomato_slices.md' 
        - Bruschetta (Ve, DF): 'appetizers/bruschetta.md'
        - Eggplant Caponata (Ve, P, DF, GF): 'appetizers/eggplant_caponata.md'
        - Italian Roasted Red Pepper Antipasto (Ve, DF): 'appetizers/roasted_red_pepper_antipasto.md'
    - Beverages:
        - Dairy-Free Eggnog: 'beverages/dairy_free_eggnog.md'
    - Breads:
        - Italian Pizza Dough (Ve, P, GF, DF): 'breads/italian_pizza_dough.md'
        - Lard Pie Crust (DF): 'breads/lard_pie_crust.md'
        - North American Pizza Crusts (Ve, P, GF, DF): 'breads/pizza_crusts.md'
        - Pretzel Sourdough Discard: ''
        - Sourdough Bagels: 'breads/sourdough_bagels.md'
        - Sourdough Bread: 'breads/sourdough_bread.md'
        - Sourdough Buns: 'breads/sourdough_buns.md'
    - Breakfasts & Brunchs:
        - Baked French Toast Casserole: 'breakfast/baked_french_toast_casserole.md'
        - French Crepe Buffet (V, DF): 'breakfast/french_crepe_buffet.md'
        - French Toast (V, DF): 'breakfast/french_toast.md'
        - Grain-Free Fruit Cereal (P, V, DF): 'breakfast/no_grain_cereal.md'
        - Oatmeal (Ve, V, DF, GF): 'breakfast/oatmeal.md'
        - Pancake (V, DF, GF): 'breakfast/pancakes.md'
        - Potatoes with eggs bowl (M, GF, DF): 'breakfast/potatoes_eggs_bowl.md'
        - Roasted Brussel Sprouts & Bacon (P, DF, GF, M) : 'sides/roasted_brussel_sprouts_bacon_apples.md'
        - Shakshuka (P, DF, GF): 'breakfast/shakshuka.md'
    - Salads:
        - Apple Green Salad (Ve, P, GF, DF): 'salad/apple_green_salad.md'
        - Broccoli Salad (P, GF, DF): 'salad/broccoli_salad.md'
        - Chicken and Rice Salad (GF, DF): 'salad/rice_chicken_salad.md'
        - Classic Coleslaw (DF, GF): 'salad/classic_coleslaw.md'
        - Cucumber, Apple, and Tomato Salad (Ve, P, GF, DF): 'salad/apple_cucumber_salad.md'
        - Green Bean Salad (Ve, P, GF): 'salad/green_bean_salad.md'
        - Macaroni Salad (DF): 'salad/macaroni_salad.md'
        - Moroccan Carrot Slaw (Ve, DF, GF): 'salad/moroccan_carrot_salad.md'
        - Potato Salad (GF, DF): 'salad/potato_salad.md'
    - Sandwiches & Burgers: 
        - Big Bhaji Burger (Ve, GF): 'sand/big_bhaji_burger.md'
        - Buffalo Cauliflower Burger (Ve, GF): 'sand/buffalo_cauliflower_burger.md'
        - Crispy Chicken Burger (M, DF): 'sand/crispy_chicken_burger.md'
        - Chipotle Chicken Club Wrap: 'sand/chipotle_chicken_wrap.md'   
        - Philly Steak Sandwich (M, DF): 'sand/philly_steak_sandwich.md'
        - Meatball Sandwich (M, DF): 'sand/meatball_sandwich.md'
    - Soups & Stews:
        - Soups:
            - Creamy Vegetables Soup (Ve, P, GF, DF): 'soups_stews/creamy_vegetable_soup.md'    
            - Chickpea/Chicken Noodle Soup (Ve, GF, DF): 'soups_stews/chickpea_noodle_soup.md'            
            - French Canadian Pea Soup (Ve, GF): 'soups_stews/soupe_pois_québécoise_french_canadian_pea_soup.md'
            - Lentil Soup (Ve, GF): 'soups_stews/lentil_soup.md'
            - Spicy Sausage White Bean Soup (P, DF, GF): 'soups_stews/spicy_sausage_white_bean_soup.md'
        - Stews/Chilis:
            - Beef Stew (M, GF, DF): 'soups_stews/beef_stew.md'
            - Chili Con Carne (M, GF, DF): 'soups_stews/chili_con_carne.md'
            - Curried Bean and Brussels Stew (Ve, P, GF): 'soups_stews/curried_bean_brussels_stew_squash.md'
            - Hungarian Goulash (V, DF, GF): 'soups_stews/hungarian_goulash.md'
            - Turkey Quinoa Chili (P, DF, GF): 'soups_stews/turkey_quinoa_chili.md'
            - Winter Lentil Stew (Ve, DF, GF): 'soups_stews/winter_lentil_stew.md'
        - Chowders:
            - Succotash Chowder (Ve, GF): 'soups_stews/succotash_chowder.md'  
    - Main Courses:
        - Asian: 
            - General Tao Chicken: 'main_course/general_tao_chicken.md'
            - Peanut Noodles (Ve, DF): 'main_course/peanut_noodles.md'
            - Spring Rolls (Ve, DF): 'main_course/spring_rolls.md'
            - Sushi Rolls (Ve, DF, GF, M): 'main_course/sushi_rolls.md'
        - Bowls:
            - Arroz Tapado (M, DF, GF): 'main_course/arroz_tapado.md'
            - Bibimbap: 'main_course/bibimbap.md'
            - General Tao Noodle Bowl (Ve, GF): 'main_course/general_tao_noodle_bowl.md'
            - Loco Moco: 'main_course/loco_moco.md'
        - Casseroles:
            - Chicken a la King Casserole (DF, GF, M): 'main_course/chicken_a_la_king_casserole.md'
            - Gumbo (M, DF): 'main_course/gumbo.md'
            - Jambalaya (P, DF, GF): 'main_course/jambalaya.md'
            - Loaded Cauliflower Bake Casserole (P, DF, GF): 'main_course/loaded_cauliflower_bake_casserole.md'
            - Sausage and Slaw Skillet (P, GF, M): 'main_course/sausage_slaw_skillet.md'
            - Sausage Casserole (P, DF, GF, M): 'main_course/sausage_casserole.md'
            - Shepherd Pie (DF, M): 'main_course/shepherd_pie.md'
            - Spanish Paella (Ve, GF): 'main_course/paella.md'
            - Taco Casserole (P, DF, M): 'main_course/taco_casserole.md'
        - Curry & Pad Thai: 
            - Coconut Chickpea Curry (Ve, GF): 'main_course/coconut_chickpea_curry.md'
            - Robyn's Chicken Red Thai Curry (P, DF, GF, M): 'main_course/robyn_red_thai_curry_chicken.md'
            - Noodle-Free Pad Thai (Ve, P, GF): 'main_course/noodle_free_pad_thai.md'
            - Vegan Pad Thai (Ve, DF): 'main_course/vegan_pad_thai.md'
        - European:
            - Schnitzel (DF, M): 'main_course/schnitzel.md'
        - Indian:
            - Aloo Mushroom Masala (Ve, GF): 'main_course/mushroom_masala.md'
            - Baingan Bharta (Ve, GF): 'main_course/baingan_bharta.md'
            - Dairy-Free Butter Chicken (P, GF, DF, M): 'main_course/dairy_free_butter_chicken.md'
        - Mediterranean: 
            - Donair: 'main_course/donair.md'
            - Falafel (Ve, GF): 'main_course/falafel.md'
            - Foul Mudammas (Ve, DF): 'main_course/foul_mudammas.md'
            - Mujaddara (Ve, DF, GF): 'main_course/mujaddara.md'
            - Samosa (M, DF): 'main_course/samosa.md'
        - Mexican: 
            - Flautas (VE, DF): 'main_course/flautas.md'
        - North American: 
            - Brisket Burnt Ends (M, GF, DF): 'main_course/brisket_burnt_ends.md'
            - Carrot Dogs (Ve, DF): 'main_course/carrot_dogs.md'
            - Chicken Nuggets (P, GF, DF): 'main_course/chicken_nuggets.md'
            - Chicken a la King (P, DF, GF): 'main_course/chicken_a_la_king.md'
            - Meat pie (Tourtière): 'main_course/meat_pie.md'
            - Tofu Quiche (Ve, GF) : 'main_course/tofu_quiche.md'
            - Roasted Cauliflower Steaks (Ve, P, GF): 'main_course/roasted_cauliflower_steaks.md'
            - Roasted Leg of Lamb (P, GF): 'main_course/roasted_leg_lamb.md'
        - Pizza: 
            - North American Pizzas: 'main_course/pizza.md'
            - Rustic Italian Pizza: 'main_course/rustic_italian _pizza.md'   
        - Pasta:
            - Cabbage Stroganoff (P, Ve, DF, GF): 'main_course/cabbage_stroganoff.md'
            - Carbonara (M): 'main_course/creamy_carbonara.md'
            - Dan Dan Chae Noodles (Ve): 'main_course/dan_japchae_noodles.md'
            - Fettuccini Alfredo (Ve, DF, GF): 'main_course/vegan_alfredo.md'
            - Lasagna (Ve, DF): 'main_course/lasagna.md'
            - Noodles with Corn and Rosemary Sauce (Ve, DF, GF): 'main_course/noodles_corn_rosemary_sauce.md'
            - Noodles with Black Bean Sauce (Ve, DF, GF): 'main_course/noodle_pepper_black_bean_sauce.md'
            - Pumpkin Penne (Ve, DF, GF): 'main_course/pumpkin_penne.md'
            - Tofu Mushroom Stroganoff (Ve, DF, GF): 'main_course/tofu_mushroom_stroganoff.md'
    - Sides:
        - Grains:
            - Baked Beans (Ve, GF): 'sides/baked_beans_instant_pot.md'
            - Black eyed peas Curry (Ve, GF): 'sides/black_eyed_peas_curry_instant_pot.md'
        - Pasta/Dumpling: 
            - spaetzle (Ve, DF): 'sides/spaetzle.md'
        - Potatoes:
            - Aloo Palak (Ve, GF): 'sides/aloo_palak.md'
            - Squished Baby Potatoes (Ve, GF): 'sides/squished_baby_potatoes.md'
        - Rice:
            -  Coconut Rice (Ve, GF): 'sides/coconut_rice.md'
            -  Dirty Rice (DF, GF, M): 'sides/dirty_rice.md'
        - Roasted Vegetables:
            - Beet Glaze (V, P, DF, GF): 'sides/beet_glaze.md'
            - Carrot Glaze (V, P, DF, GF): 'sides/carrot_glaze.md'
            - Harvest Maple Carrots & Apples (V, P, DF, GF): 'sides/harvest_carrots_apples.md'
            - Roasted Brussel Sprouts with Bacon and Apples (P, DF, GF, M): 'sides/roasted_brussel_sprouts_bacon_apples.md'
            - Roasted Butternut Squash (Ve, P, GF): 'sides/roasted_butternut_squash.md'
            - Roasted Maple Squash (Ve, P, GF): 'sides/roasted_maple_squash.md'
            - Roasted Radishes (Ve, P, GF): 'sides/roasted_radishes.md'
        - Vegetable:
            - Grilled Onions (Ve, P, GF): 'sides/grilled_onions.md'
            - Fried Green Tomatoes (Ve): 'sides/fried_green_tomatoes.md'
            - Mushroom spinach potstickers (Ve, P, GF): 'sides/mushroom_spinach_potstickers.md'
            - Stir Fry Bean Sprouts with Fried Garlic (Ve, P, GF): 'sides/stir_fry_bean_sprouts.md'
            - Succotash (Ve, GF): 'sides/succotash.md'
            - Pan-fried Asparagus (Ve, P, GF): ''
            - Italian Style Zucchini and Mushroom (P, Ve, GF): 'sides/italian_zucchini_mushrooms.md'
            - Vegetables Fritters (Ve, P, GF): 'sides/vegetables_fritters.md'                 
    - Sauces/Dips/Cheezes:
        - Cheezes:
            - Cheeze Sauce (Ve, GF): 'sauces/cheeze_sauce.md'
            - Vegan Heavy Cream (Ve, GF, P, GF): 'sauces/vegan_heavy_cream.md'
            - Vegan Mozzarella (Ve, GF, P, GF): 'sauces/vegan_mozzarella.md'
            - Vegan Parmesan (Ve, GF, P, GF): 'sauces/vegan_parmesan.md'
            - Vegan Ricotta (Ve, GF, P, GF): 'sauces/vegan_ricotta.md'
            - Vegan Sour Cream (Ve, GF, P, GF): 'sauces/vegan_sour_cream.md'
        - Dips:
            - Buffalo Chicken Dip (P, DF, GF): 'sauces/buffalo_chicken_dip.md'
            - Cretons (P, DF, GF): 'sauces/cretons.md'
            - Roasted Salsa (P, Ve, GF): 'sauces/roasted_salsa.md'
            - Baked Spinach Dip (Ve, GF): 'sauces/vegan_baked_spinach_dip.md'
        - Sauces:
            - Authentic Italian Tomato Sauce (P, Ve, GF): 'sauces/italian_tomato_sauce.md'  
            - Honey Garlic Sauce (P, Ve, GF): 'sauces/honey_garlic_sauce.md'  
            - Pizza Sauce (P, Ve, GF): 'sauces/pizza_sauce.md'
            - Spaghetti Sauce (P, GF): 'sauces/spaghetti_sauce.md'
            - Basic Tomato Cream Sauce:  'sauces/tomato_cream.md' 
    - Snacks:
        - Popsicles: 
            - Fruity Coconut Popsicles (P, Ve, GF): 'snacks/fruity_coconut_popsicles.md'
            - Chocolate Nut Butter Banana Popsicles(P, Ve, GF): 'snacks/chocolate_nut_butter_popsicles.md'
    - Desserts:
        - Cake/Cookies:
            - Banana Bread: 'desserts/banana_bread.md'
            - Indoors Campfire Treats: 'desserts/campfire_treats.md'
            - Mug Brownies: 'desserts/mug_brownie.md'
            - Cheese cake (Ve, DF): 'desserts/vegan_cheese_cake.md'
            - Gingersnap cookies (GF, DF): 'desserts/gf_gingersnap_cookies.md'
            - Zucchini Bread: 'desserts/zucchini_bread.md'
        - Crust:
            - Gingersnap Pie Crust (GF, DF): 'desserts/gingersnap_pie_crust.md'
        - Frosting:
            - For Cake and Cupcake: 'desserts/vegan_frosting.md'
        - Fudge:
            - Vegan Chocolate (Ve, DF): 'desserts/vegan_fudge.md'
        - Pastries:
            - Indoors Campfire treats: 'desserts/campfire_treats.md'
            - Pets de soeur: 'desserts/pets_de_soeur.md'
        - Pie:
            - Pumpkin Pie (Ve, DF): 'desserts/vegan_pumpkin_pie.md'
            - Lemon Meringue Pie (DF): ''
        - Toppings:
            - Whipped Cream: 'desserts/coconut_whipped_cream.md' 
- Basics:
    - Broth:
        - Bone Broth: ''
        - Vegetable Broth: ''
    - Fermentation:
        - Kimchi: ''
        - Sourkraut: ''
        - Jun: ''
        - Kombucha: ''      
    - Pasta:
        - Authentic Italian Egg Pasta: ''
        - Authentic Italian Gnocchi: ''  
    - Homemade Sausages: 'basics/sausage.md'
    - Homemade Mayonnaise: 'basics/homemade_mayo.md'
    - Sourdough Starter:  'basics/sourdough_starter.md'   
    - Tofu:
        - Tofu Marinades: 'basics/marinating_tofu.md'
        - How to Make Tofu:
            - Soy Tofu: ''
            - Chickpea Tofu: ''
    - Tempeh: '' 
- About: ''
